import type { Metadata } from "next";
import SearchComponenet from "@/components/SearchComponenet";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",  // Updated description
};

type LayoutProps = {
    children: React.ReactNode;
    modal: React.ReactNode;
}

export default function Layout({ children ,modal }: LayoutProps) {
    return (
        <>

            <SidebarProvider>
                <AppSidebar />
                <main className="px-10 py-4 w-full ">
                    <SidebarTrigger />
                    <div className="dashboard flex flex-col gap-10">
                        <SearchComponenet />
                        {children}
                        {modal}
                    </div>
                </main>
            </SidebarProvider>

        </>
    )
}
