import type { Metadata } from "next";
import SearchComponenet from "@/components/SearchComponenet";


export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",  // Updated description
};

type LayoutProps ={ 
    children: React.ReactNode;    
 }

export default function Layout({ children}:LayoutProps) {
    return (
        <>
            <div className="dashboard flex flex-col gap-10">
                <SearchComponenet />
                {children}
            </div>
        </>
    )
}
