import type { Metadata } from 'next';
import './globals.css';
import { Poppins } from 'next/font/google';
import Providers from '@/components/providers';

const poppins = Poppins({
    weight: ['400', '700', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Exam App',
    description: 'Generated by create next app', // Updated description
};
export default function RootLayout({
    children,
    admin,
    student,
}: Readonly<{
    children: React.ReactNode;
    admin: React.ReactNode;
    student: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className={`${poppins.className} `}>
                    <Providers>
                        {children}
                        {/* Parallel routes will be rendered based on active route */}
                        {admin}
                        {student}
                    </Providers>
                </body>
            </html>
        </>
    );
}
