import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Poppins } from "next/font/google";
import Providers from "@/components/providers";


const poppins = Poppins({
  weight: ['400', '700', "900"],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by create next app",  // Updated description
};

export default function RootLayout({
  children, student
}: Readonly<{
  children: React.ReactNode;
  student: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${poppins.className} `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            themes={["dark", "light"]}
            disableTransitionOnChange
          >
            <Providers>

              <main>
                {children}
                {student}
              </main>

            </Providers>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
