import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


export const metadata: Metadata = {
    title: "Exam App",
    description: "Generated by create next app",  // Updated description
};

export default function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>

            <SidebarProvider>
                <AppSidebar />
                <main className="px-10 py-4 w-full ">
                    <SidebarTrigger />
                    {children}
                </main>
            </SidebarProvider>
            {/* <Sidebar /> */}
            {/* <main className='ml-[300px] h-screen p-4'>{children}</main> */}
        </>
    )
}
