import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";


export const metadata: Metadata = {
    title: "Exam App",
    description: "Generated by create next app",  // Updated description
};

export default function Layout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <>
            <Sidebar />
            <main className='ml-[300px] h-screen p-4'>{children}</main>
        </>
    )
}
